export enum BUTTONS {
    ADD_FILE,
    ADD_FOLDER,
    DELETE,
    RENAME,
}

export enum MODALS {
    NULL,
    NEW_FILE,
    NEW_FOLDER,
    RENAME_FILE,
    RENAME_FOLDER,
    DELETE_FILE,
    DELETE_FOLDER,
    PERMANENT_DELETE_FILE,
    PERMANENT_DELETE_FOLDER,
    EMPTY_BIN,
}
